"""
Django settings for Alejandria project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from datetime import timedelta
from pathlib import Path
import os
from dotenv import load_dotenv
from corsheaders.defaults import default_headers
from django.core.exceptions import ImproperlyConfigured
from django.core.management.utils import get_random_secret_key

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent

# Cargar variables de entorno desde .env si existe
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'true').lower() in ('true', '1', 'yes')


def _obtener_secret_key():
    """Devuelve la SECRET_KEY de Django (F02 pentest).

    - Si DJANGO_SECRET_KEY está definida en el entorno, se usa tal cual.
    - Si no está definida y DEBUG es True (desarrollo/tests sin .env), se
      genera una clave aleatoria distinta en cada arranque: es segura para
      desarrollo porque las sesiones/firmas no persisten entre reinicios.
    - Si no está definida y DEBUG es False, se aborta el arranque: en
      producción la clave es OBLIGATORIA y no se permite un fallback.
    """
    clave = os.environ.get('DJANGO_SECRET_KEY')
    if clave:
        return clave
    if DEBUG:
        return get_random_secret_key()
    raise ImproperlyConfigured(
        "DJANGO_SECRET_KEY no está definida. Copia .env.example a .env y "
        "genera una clave segura (python -c \"from django.core.management."
        "utils import get_random_secret_key; print(get_random_secret_key())\")."
    )


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = _obtener_secret_key()

# F05 pentest: whitelist de hosts por entorno. Sin DJANGO_ALLOWED_HOSTS se usa
# un default seguro para desarrollo local ('testserver' lo necesita el test
# client de Django). En producción define DJANGO_ALLOWED_HOSTS con los dominios
# reales separados por comas; NUNCA uses '*' fuera de desarrollo.
ALLOWED_HOSTS = [
    h.strip() for h in os.environ.get(
        'DJANGO_ALLOWED_HOSTS',
        'localhost,127.0.0.1,testserver',
    ).split(',')
    if h.strip()
]


# F06 pentest: CORS por whitelist de orígenes, no ALLOW_ALL.
# - DJANGO_CORS_ALLOWED_ORIGINS (separada por comas) define los orígenes en
#   producción/desarrollo; sin la variable se usa un default seguro de
#   desarrollo (frontend Ionic dev en el puerto 8100).
# - DJANGO_CORS_ALLOW_ALL se conserva SOLO por compatibilidad con despliegues
#   anteriores y su default es False: en producción debe permanecer False.
#   Preferir siempre la whitelist explícita.
_CORS_ALLOW_ALL = os.environ.get('DJANGO_CORS_ALLOW_ALL', 'false').lower() in ('true', '1', 'yes')
CORS_ALLOW_ALL_ORIGINS = _CORS_ALLOW_ALL
CORS_ALLOWED_ORIGINS = [
    o.strip() for o in os.environ.get(
        'DJANGO_CORS_ALLOWED_ORIGINS',
        'http://localhost:8100,http://127.0.0.1:8100',
    ).split(',')
    if o.strip()
]
CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "POST",
    "PUT",
    "OPTIONS",
    "PATCH"

]

CORS_ALLOW_HEADERS = list(default_headers) + [
    "Authorization"
]

# --------------------------------------------------------------------------- #
# Seguridad de transporte (F07 pentest)
# Flags leídos del entorno: apagados por defecto (desarrollo sobre HTTP) y
# activados desde .env en producción, donde el HTTPS lo termina el
# proxy/balanceador. SECURE_SSL_REDIRECT y las cookies Secure requieren que
# la app se sirva realmente por HTTPS.
# --------------------------------------------------------------------------- #
SECURE_SSL_REDIRECT = os.environ.get('DJANGO_SECURE_SSL_REDIRECT', 'false').lower() in ('true', '1', 'yes')
SESSION_COOKIE_SECURE = os.environ.get('DJANGO_SESSION_COOKIE_SECURE', 'false').lower() in ('true', '1', 'yes')
CSRF_COOKIE_SECURE = os.environ.get('DJANGO_CSRF_COOKIE_SECURE', 'false').lower() in ('true', '1', 'yes')
# HSTS: 0 (o ausente) en desarrollo; segundos de vigencia (>0) en producción.
SECURE_HSTS_SECONDS = int(os.environ.get('DJANGO_SECURE_HSTS_SECONDS', '0'))
SECURE_HSTS_INCLUDE_SUBDOMAINS = os.environ.get('DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS', 'false').lower() in ('true', '1', 'yes')
SECURE_HSTS_PRELOAD = os.environ.get('DJANGO_SECURE_HSTS_PRELOAD', 'false').lower() in ('true', '1', 'yes')
# Seguras en cualquier entorno (sin impacto en desarrollo):
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = 'same-origin'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

# Third party apps
    'corsheaders',
    'rest_framework',
    'drf_spectacular',

    #LA app 
    'biblioteca',
]

# Configuración de drf-spectacular (generación del esquema OpenAPI)
SPECTACULAR_SETTINGS = {
    'TITLE': 'Alejandría API',
    'DESCRIPTION': 'API de gestión de la biblioteca Alejandría.',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    # /swagger/ y /redoc/ son públicos (documentación abierta por decisión del equipo).
    'SERVE_PERMISSIONS': ['rest_framework.permissions.AllowAny'],
}

# Configuración de Django REST Framework
REST_FRAMEWORK = {
    # F01 pentest: la API ya no es anónima; se autentica con JWT.
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    # F04 pentest: límites de requests por hora para mitigar el spam ilimitado.
    # - AnonRateThrottle protege los endpoints públicos (p.ej. POST /token/
    #   contra fuerza bruta de credenciales). En los endpoints autenticados el
    #   chequeo de permisos (IsAuthenticated) responde 401 ANTES del throttle,
    #   por lo que un anónimo jamás consume su cuota ahí.
    # - UserRateThrottle limita el tráfico por usuario autenticado (1000/h);
    #   también acota el spam de escritura (POST/PUT) de cada cuenta.
    # Decisión: NO se añade ScopedRateThrottle para acciones de creación: el
    # scope se aplica a TODA la vista (también a los GET de lectura) y el
    # límite general por usuario ya pone tope al spam de escritura. Si en el
    # futuro se quiere un límite más estricto solo para POST, conviene un
    # throttle personalizado por acción, no un scope de vista.
    # Nota: el throttle usa la caché de Django (LocMemCache en desarrollo);
    # en producción conviene una caché compartida como Redis.
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/hour',
        'user': '1000/hour',
    },
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

# Configuración de SimpleJWT (tokens de acceso y refresco)
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': False,
}

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
