"""
Django settings for Alejandria project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from datetime import timedelta
from pathlib import Path
import os
from dotenv import load_dotenv
from corsheaders.defaults import default_headers
from django.core.exceptions import ImproperlyConfigured
from django.core.management.utils import get_random_secret_key

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent

# Cargar variables de entorno desde .env si existe
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'true').lower() in ('true', '1', 'yes')


def _obtener_secret_key():
    """Devuelve la SECRET_KEY de Django (F02 pentest).

    - Si DJANGO_SECRET_KEY está definida en el entorno, se usa tal cual.
    - Si no está definida y DEBUG es True (desarrollo/tests sin .env), se
      genera una clave aleatoria distinta en cada arranque: es segura para
      desarrollo porque las sesiones/firmas no persisten entre reinicios.
    - Si no está definida y DEBUG es False, se aborta el arranque: en
      producción la clave es OBLIGATORIA y no se permite un fallback.
    """
    clave = os.environ.get('DJANGO_SECRET_KEY')
    if clave:
        return clave
    if DEBUG:
        return get_random_secret_key()
    raise ImproperlyConfigured(
        "DJANGO_SECRET_KEY no está definida. Copia .env.example a .env y "
        "genera una clave segura (python -c \"from django.core.management."
        "utils import get_random_secret_key; print(get_random_secret_key())\")."
    )


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = _obtener_secret_key()

ALLOWED_HOSTS = [
    h.strip() for h in os.environ.get('DJANGO_ALLOWED_HOSTS', '*').split(',')
]


#Cors
CORS_ALLOW_ALL_ORIGINS = os.environ.get('DJANGO_CORS_ALLOW_ALL', 'true').lower() in ('true', '1', 'yes')
CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "POST",
    "PUT",
    "OPTIONS",
    "PATCH"

]

CORS_ALLOW_HEADERS = list(default_headers) + [
    "Authorization"
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

# Third party apps
    'corsheaders',
    'rest_framework',
    'drf_spectacular',

    #LA app 
    'biblioteca',
]

# Configuración de drf-spectacular (generación del esquema OpenAPI)
SPECTACULAR_SETTINGS = {
    'TITLE': 'Alejandría API',
    'DESCRIPTION': 'API de gestión de la biblioteca Alejandría.',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    # F11 pentest: el schema OpenAPI (/swagger/, /redoc/) exige autenticación.
    'SERVE_PERMISSIONS': ['rest_framework.permissions.IsAuthenticated'],
}

# Configuración de Django REST Framework
REST_FRAMEWORK = {
    # F01 pentest: la API ya no es anónima; se autentica con JWT.
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

# Configuración de SimpleJWT (tokens de acceso y refresco)
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': False,
}

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
