# Generated by Django 6.1 on 2026-08-22 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='devuelto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='fecha_devolucion_real',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
