# Generated by Django 5.2.17 on 2026-08-23 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0003_categoria_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
