# Generated by Django 5.2.17 on 2026-08-23 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0004_prestamo_fecha_vencimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='devuelto_vencido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='fecha_devolucion_real',
            field=models.DateField(blank=True, null=True),
        ),
    ]
